site:
  title: Docs
  url: https://docs.tigergraph.com/
  start_page: tigergraph-server::intro:index.adoc
  robots: |
    User-agent: *
    Sitemap: https://docs.tigergraph.com/sitemap.xml
content:
  sources:
  - url: https://github.com/tigergraph/doc-site.git
    branches: [main]
    start_paths: home
  - url: https://github.com/tigergraph/server-docs.git
    branches: ["ja-3.7"]
  - url: https://github.com/tigergraph/gui-docs.git
    branches: [3.7]
  - url: https://github.com/tigergraph/cloud-docs.git
    branches: main
  - url: https://github.com/tigergraph/tigdsl-docs.git
    branches: ja-1.0
  - url: https://github.com/tigergraph/gsql-docs.git
    branches: ["ja-3.7"]
  - url: https://github.com/tigergraph/tigergraphql.git
    branches: [main, 0.8]
  - url: https://github.com/tigergraph/mlworkbench-docs.git
    branches: [main]
  - url: https://github.com/tigergraph/pytigergraph-docs
    branches: [1.0, 1.1]
  - url: https://github.com/tigergraph/insights-docs
    branches: [main]
ui:
  bundle:
    url: https://github.com/tigergraph/antora-ui/blob/jp/build/ui-bundle.zip?raw=true
    snapshot: true
asciidoc:
  attributes:
    page-component-order: '!home, cloud, tigergraph-server, gsql-ref, gui, graph-ml, ml-workbench, pytigergraph, graphql'
  extensions:
  - ./libs/tabs-block.js
urls:
  html_extension_style: drop
  latest_version_segment_strategy: redirect:to
  latest_version_segment: current
  redirect_facility: netlify