[build]

    publish = "build/site/"
    command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval'; script-src * 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com; connect-src * 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src *; style-src * 'unsafe-inline';"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-Robots-Tag = "noindex"

[[redirects]]
    from = "/jp/*"
    to = "https://jp-tgdocs.netlify.app/:splat"
    status = 200

# redirects for gui
[[redirects]]
    from = "/ui/graphstudio"
    to = "/gui/current"

[[redirects]]
    from = "/ui/admin-portal/*"
    to = "/gui/current/admin-portal/:splat"

[[redirects]]
    from = "/ui/graphstudio/*"
    to = "/gui/current/graphstudio/:splat"

[[redirects]]
    from = "/tigergraph-cloud/tigergraph-cloud-faqs"
    to = "/cloud/support/faqs"

# redirects for cloud
[[redirects]]
    from = "/cloud/tigergraph-cloud-faqs"
    to = "/cloud/support/faqs"

# redirects for language reference
[[redirects]]
    from = "/dev/gsql-ref/querying/func"
    to = "/gsql-ref/current/querying/func/readme"

[[redirects]]
    from = "/gsql-ref/current/querying/operators-functions-and-expressions"
    to = "/gsql-ref/current/querying/operators-and-expressions"

[[redirects]]
    from = "/dev/gsql-ref"
    to = "/gsql-ref/current/intro/intro"

[[redirects]]
    from = "/dev/gsql-ref/querying/select-statement"
    to = "/gsql-ref/current/querying/select-statement/readme"

[[redirects]]
    from = "/dev/gsql-ref/*"
    to = "/gsql-ref/current/:splat"

[[redirects]]
    from = "/start/gsql-101"
    to = "/gsql-ref/current/tutorials/gsql-101/readme"

[[redirects]]
    from = "/start/gsql-101/*"
    to = "/gsql-ref/current/tutorials/gsql-101/:splat"

[[redirects]]
    from = "/start/gsql-102"
    to = "/gsql-ref/current/tutorials/pattern-matching/readme"

[[redirects]]
    from = "/start/gsql-102/*"
    to = "/gsql-ref/current/tutorials/pattern-matching/:splat"

[[redirects]]
    from = "/start/accumulators-tutorial"
    to = "/gsql-ref/current/tutorials/accumulators-tutorial"

# redirects for server
[[redirects]]
    from = "/dev/restpp-api"
    to = "/tigergraph-server/current/api/intro"

[[redirects]]
    from = "/admin/admin-guide/user-access/user-privileges-and-authentication"
    to = "/tigergraph-server/current/user-access/readme"

[[redirects]]
    from = "/tigergraph-server/current/api/restpp-requests"
    to = "/tigergraph-server/current/api/intro"

[[redirects]]
    from = "/tigergraph-server/current/user-access/single-sign-on"
    to = "/tigergraph-server/current/user-access/sso"

[[redirects]]
    from = "/dev/restpp-api/*"
    to = "/tigergraph-server/current/api/:splat"

[[redirects]]
    from = "/admin/admin-guide/install-and-config/*"
    to = "/tigergraph-server/current/installation/:splat"

[[redirects]]
    from = "/admin/admin-guide/user-access/*"
    to = "/tigergraph-server/current/user-access/:splat"

# redirects for graph-ml
[[redirects]]
    from = "/tigergraph-platform-overview/graph-algorithm-library"
    to = "/graph-ml/current/intro/overview"